plugins {
    id 'com.android.application' version '8.6.1'
}

android {
    namespace 'com.traderbusinesscontrol.client'
    compileSdk 35

    defaultConfig {
        applicationId 'com.traderbusinesscontrol.client'
        minSdk 24
        targetSdk 35
        versionCode 2
        versionName '1.1'
    }
}

dependencies {
    implementation 'androidx.webkit:webkit:1.17.1'
}
